# Add configuration values here, as shown below.

development:
  backoffice_url: http://api-preprod.caribeapuesta.com
  iframe_url: http://localhost:3000
  VES_USER: 'userwebtest'
  VES_PSSW: '0000'
  USD_USER: 'TESTPROD'
  USD_PSSW: '123456'
production:
  iframe_url: http://143.198.65.44:3000
  backoffice_url: http://api-preprod.caribeapuesta.com
  VES_USER: 'TESTPRODBS'
  VES_PSSW: '123456'
  USD_USER: 'TESTPROD'
  USD_PSSW: '123456'
